FROM oven/bun:1.3.8 AS deps

WORKDIR /app/beerbot

COPY package.json ./
COPY bun.lock ./

RUN bun install --frozen-lockfile

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development

EXPOSE 3000

CMD [ "bun", "run", "dev" ]
